-- 기존 테이블이 있다면 삭제하고 다시 만듭니다 (깨끗한 상태로 시작)
drop table if exists portfolio;

-- 1. 포트폴리오 데이터를 저장할 테이블 생성
-- "generated always" 대신 "generated by default"를 사용하여 ID를 직접 지정할 수 있게 변경했습니다.
create table portfolio (
  id bigint primary key generated by default as identity,
  content jsonb
);

-- 2. 누구나 읽고 쓸 수 있도록 권한 설정 (RLS)
alter table portfolio enable row level security;

create policy "Enable all access" 
on portfolio for all 
using (true) 
with check (true);

-- 3. 초기 데이터(빈 껍데기) 생성
-- 이제 오류 없이 1번 ID로 생성됩니다.
insert into portfolio (id, content)
values (1, '{}');
